export interface StaticDocPage {
  slug: string;
  title: string;
  summary: string;
  markdown: string;
}

export const getStartedDocs: StaticDocPage[] = [
  {
    slug: "overview",
    title: "Overview",
    summary: "Guardrails turns repository conventions into runnable checks, grouped for easy adoption.",
    markdown: [
      "## What Guardrails Is",
      "",
      "Guardrails is a lightweight convention runner for package-level checks. Each rule owns its own file search, emits diagnostics, and can be bundled into reusable groups.",
      "",
      "## Core Concepts",
      "",
      "- **Rules** are the smallest units of enforcement such as path naming, README structure, or required scripts.",
      "- **Groups** bundle related rules behind one `inherit` entry so packages can opt into a baseline quickly.",
      "- **Docs sidecars** live next to rule implementations, which lets the docs site stay in sync with the source tree.",
      "",
      "## How To Read These Docs",
      "",
      "Start with Setup if you need a quick install and config path. After that, use Groups to choose a baseline and Rules to inspect individual checks in detail.",
    ].join("\n"),
  },
  {
    slug: "setup",
    title: "Setup",
    summary: "Install Guardrails, add a package-root config, and run the CLI against your package.",
    markdown: [
      "## 1. Install The Package",
      "",
      "Add Guardrails to the workspace or package where you want to run the checks.",
      "",
      "```bash",
      "pnpm add -D @two-pebble/guard",
      "```",
      "",
      "## 2. Add A `guard.json` File",
      "",
      "Start from a group when possible so you get a coherent baseline instead of enabling individual rules one by one.",
      "",
      "```json",
      "{",
      '  "inherit": "@group/guardrails-typescript"',
      "}",
      "```",
      "",
      "You can also layer in targeted rules with explicit options:",
      "",
      "```json",
      "{",
      '  "inherit": "@group/guardrails-typescript",',
      '  "additional": {',
      '    "@rule/required-scripts": {',
      '      "requiredScripts": ["build", "test", "typecheck"]',
      "    }",
      "  }",
      "}",
      "```",
      "",
      "## 3. Run The CLI",
      "",
      "Run Guardrails from the package root so root-scoped rules can resolve files like `README.md` and `package.json` correctly.",
      "",
      "```bash",
      "pnpm exec guardrails",
      "```",
      "",
      "If you are working inside this repository directly, the local package command still works:",
      "",
      "```bash",
      "pnpm --dir packages/guardrails run guard",
      "```",
    ].join("\n"),
  },
];
