import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, relative, resolve } from "node:path";
import { glob } from "tinyglobby";

export interface RuleDoc {
  slug: string;
  title: string;
  summary: string;
  markdown: string;
  ruleSourcePath: string;
  docsSourcePath: string;
}

export async function collectRuleDocs(docsPackageDir: string) {
  const repositoryRoot = resolve(docsPackageDir, "../..");
  const docsPaths = await glob("packages/guardrails/src/rules/**/docs.md", {
    absolute: true,
    cwd: repositoryRoot,
  });

  const ruleDocs = docsPaths.sort().map((docsPath) => {
    const relativeDocsPath = normalizePath(relative(repositoryRoot, docsPath));
    const ruleDirectory = dirname(relativeDocsPath);
    const slug = basename(ruleDirectory);
    const markdown = readFileSync(docsPath, "utf-8").trim();

    return {
      slug,
      title: formatRuleTitle(slug),
      summary: extractSummary(markdown),
      markdown,
      ruleSourcePath: `${ruleDirectory}/rule.ts`,
      docsSourcePath: relativeDocsPath,
    } satisfies RuleDoc;
  });

  return ruleDocs;
}

export async function writeGeneratedRuleDocs(docsPackageDir: string) {
  const ruleDocs = await collectRuleDocs(docsPackageDir);
  const targetPath = resolve(docsPackageDir, "src/generated/rule-docs.ts");

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, buildGeneratedModule(ruleDocs));
}

export async function writeStaticRulePages(docsPackageDir: string) {
  const ruleDocs = await collectRuleDocs(docsPackageDir);
  const distDirectory = resolve(docsPackageDir, "dist");
  const indexHtmlPath = resolve(distDirectory, "index.html");
  const notFoundPath = resolve(distDirectory, "404.html");

  copyFileSync(indexHtmlPath, notFoundPath);

  for (const ruleDoc of ruleDocs) {
    const pageDirectory = resolve(distDirectory, "rules", ruleDoc.slug);
    mkdirSync(pageDirectory, { recursive: true });
    copyFileSync(indexHtmlPath, resolve(pageDirectory, "index.html"));
    writeFileSync(resolve(pageDirectory, "docs.md"), `${ruleDoc.markdown}\n`);
  }
}

export function buildGeneratedModule(ruleDocs: RuleDoc[]) {
  return [
    "// This file is generated by packages/docs/scripts/generate-rule-docs.ts.",
    "export interface RuleDoc {",
    "  slug: string;",
    "  title: string;",
    "  summary: string;",
    "  markdown: string;",
    "  ruleSourcePath: string;",
    "  docsSourcePath: string;",
    "}",
    "",
    "export const ruleDocs: RuleDoc[] = [",
    ruleDocs.map((ruleDoc) => buildRuleDocLiteral(ruleDoc)).join(",\n"),
    "];",
    "",
  ].join("\n");
}

export function formatRuleTitle(slug: string) {
  return slug
    .split("-")
    .filter((segment) => segment.length > 0)
    .map((segment) => segment[0].toUpperCase() + segment.slice(1))
    .join(" ");
}

function extractSummary(markdown: string) {
  const blocks = markdown
    .split(/\n\s*\n/g)
    .map((block) => block.trim())
    .filter((block) => block.length > 0);

  for (const block of blocks) {
    if (block.startsWith("#") || block.startsWith("```")) {
      continue;
    }

    return block.replace(/\s+/g, " ");
  }

  throw new Error("Rule docs must contain at least one prose paragraph.");
}

function normalizePath(path: string) {
  return path.replaceAll("\\", "/");
}

function buildRuleDocLiteral(ruleDoc: RuleDoc) {
  return [
    "  {",
    `    slug: ${JSON.stringify(ruleDoc.slug)},`,
    `    title: ${JSON.stringify(ruleDoc.title)},`,
    `    summary: ${JSON.stringify(ruleDoc.summary)},`,
    `    markdown: ${JSON.stringify(ruleDoc.markdown)},`,
    `    ruleSourcePath: ${JSON.stringify(ruleDoc.ruleSourcePath)},`,
    `    docsSourcePath: ${JSON.stringify(ruleDoc.docsSourcePath)},`,
    "  }",
  ].join("\n");
}
