import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { glob } from "tinyglobby";
import { getStartedDocs } from "../src/content";

export interface RuleDoc {
  slug: string;
  title: string;
  summary: string;
  markdown: string;
  ruleSourcePath: string;
  docsSourcePath: string;
}

export interface GroupDoc {
  slug: string;
  title: string;
  summary: string;
  markdown: string;
  ruleSlugs: string[];
}

export async function collectRuleDocs(docsPackageDir: string) {
  const repositoryRoot = resolve(docsPackageDir, "../..");
  const docsPaths = await glob("packages/guardrails/src/rules/**/docs.md", {
    absolute: true,
    cwd: repositoryRoot,
  });

  const ruleDocs = docsPaths.sort().map((docsPath) => {
    const relativeDocsPath = normalizePath(relative(repositoryRoot, docsPath));
    const ruleDirectory = dirname(relativeDocsPath);
    const slug = basename(ruleDirectory);
    const markdown = readFileSync(docsPath, "utf-8").trim();

    return {
      slug,
      title: formatRuleTitle(slug),
      summary: extractSummary(markdown),
      markdown,
      ruleSourcePath: `${ruleDirectory}/rule.ts`,
      docsSourcePath: relativeDocsPath,
    } satisfies RuleDoc;
  });

  return ruleDocs;
}

export async function writeGeneratedRuleDocs(docsPackageDir: string) {
  const ruleDocs = await collectRuleDocs(docsPackageDir);
  const groupDocs = await collectGroupDocs(docsPackageDir, ruleDocs);
  const targetPath = resolve(docsPackageDir, "src/generated/rule-docs.ts");

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, buildGeneratedModule(ruleDocs, groupDocs));
}

export async function writeStaticRulePages(docsPackageDir: string) {
  const ruleDocs = await collectRuleDocs(docsPackageDir);
  const groupDocs = await collectGroupDocs(docsPackageDir, ruleDocs);
  const distDirectory = resolve(docsPackageDir, "dist");
  const indexHtmlPath = resolve(distDirectory, "index.html");
  const notFoundPath = resolve(distDirectory, "404.html");

  copyFileSync(indexHtmlPath, notFoundPath);

  for (const directory of collectStaticPageDirectories(distDirectory, groupDocs, ruleDocs)) {
    mkdirSync(directory, { recursive: true });
    copyFileSync(indexHtmlPath, resolve(directory, "index.html"));
  }

  for (const ruleDoc of ruleDocs) {
    const pageDirectory = resolve(distDirectory, "rules", ruleDoc.slug);
    writeFileSync(resolve(pageDirectory, "docs.md"), `${ruleDoc.markdown}\n`);
  }
}

export async function collectGroupDocs(docsPackageDir: string, ruleDocs: RuleDoc[]) {
  const groupEntries = await loadGroupEntries(docsPackageDir);

  return groupEntries.map((groupEntry) => {
    const title = formatRuleTitle(groupEntry.slug);
    const markdown = buildGroupMarkdown(groupEntry.slug, title, groupEntry.ruleSlugs, ruleDocs);

    return {
      slug: groupEntry.slug,
      title,
      summary: extractSummary(markdown),
      markdown,
      ruleSlugs: groupEntry.ruleSlugs,
    } satisfies GroupDoc;
  });
}

export function buildGeneratedModule(ruleDocs: RuleDoc[], groupDocs: GroupDoc[]) {
  return [
    "// This file is generated by packages/docs/scripts/generate-rule-docs.ts.",
    "// biome-ignore-all lint/suspicious/noTemplateCurlyInString: generated markdown can include literal template-placeholder examples.",
    "export interface RuleDoc {",
    "  slug: string;",
    "  title: string;",
    "  summary: string;",
    "  markdown: string;",
    "  ruleSourcePath: string;",
    "  docsSourcePath: string;",
    "}",
    "",
    "export interface GroupDoc {",
    "  slug: string;",
    "  title: string;",
    "  summary: string;",
    "  markdown: string;",
    "  ruleSlugs: string[];",
    "}",
    "",
    "export const ruleDocs: RuleDoc[] = [",
    ruleDocs.map((ruleDoc) => buildRuleDocLiteral(ruleDoc)).join(",\n"),
    "];",
    "",
    "export const groupDocs: GroupDoc[] = [",
    groupDocs.map((groupDoc) => buildGroupDocLiteral(groupDoc)).join(",\n"),
    "];",
    "",
  ].join("\n");
}

export function formatRuleTitle(slug: string) {
  const knownTitle = getKnownTitle(slug);
  if (knownTitle) {
    return knownTitle;
  }

  return slug
    .split("-")
    .filter((segment) => segment.length > 0)
    .map((segment) => formatTitleSegment(segment))
    .join(" ");
}

function extractSummary(markdown: string) {
  const blocks = markdown
    .split(/\n\s*\n/g)
    .map((block) => block.trim())
    .filter((block) => block.length > 0);

  for (const block of blocks) {
    if (block.startsWith("#") || block.startsWith("```")) {
      continue;
    }

    return block.replace(/\s+/g, " ");
  }

  throw new Error("Rule docs must contain at least one prose paragraph.");
}

function normalizePath(path: string) {
  return path.replaceAll("\\", "/");
}

async function loadGroupEntries(docsPackageDir: string) {
  const repositoryRoot = resolve(docsPackageDir, "../..");
  const modulePath = pathToFileURL(resolve(repositoryRoot, "packages/guardrails/src/consts.ts")).href;
  const loaded = (await import(modulePath)) as {
    groups: Array<{ name: string; rules(): Array<{ rule: string }> }>;
  };

  return loaded.groups.map((group) => ({
    slug: group.name,
    ruleSlugs: group.rules().map((entry) => entry.rule),
  }));
}

function buildGroupMarkdown(slug: string, title: string, ruleSlugs: string[], ruleDocs: RuleDoc[]) {
  const ruleTitles = ruleSlugs.map((ruleSlug) => {
    const ruleDoc = ruleDocs.find((entry) => entry.slug === ruleSlug);
    return ruleDoc ? `- \`${ruleSlug}\` - ${ruleDoc.summary}` : `- \`${ruleSlug}\``;
  });

  return [
    "## What It Includes",
    "",
    `${title} bundles ${ruleSlugs.length} related rule${ruleSlugs.length === 1 ? "" : "s"} into one opt-in group.`,
    "",
    "## Enable This Group",
    "",
    "```json",
    "{",
    `  "inherit": "@group/${slug}"`,
    "}",
    "```",
    "",
    "## Included Rules",
    "",
    ...ruleTitles,
  ].join("\n");
}

function collectStaticPageDirectories(distDirectory: string, groupDocs: GroupDoc[], ruleDocs: RuleDoc[]) {
  return [
    ...getStartedDocs.map((page) => resolve(distDirectory, "get-started", page.slug)),
    resolve(distDirectory, "groups"),
    ...groupDocs.map((groupDoc) => resolve(distDirectory, "groups", groupDoc.slug)),
    resolve(distDirectory, "rules"),
    ...ruleDocs.map((ruleDoc) => resolve(distDirectory, "rules", ruleDoc.slug)),
  ];
}

function formatTitleSegment(segment: string) {
  if (segment === "md") {
    return "MD";
  }

  if (segment === "readme") {
    return "README";
  }

  if (segment === "typescript") {
    return "TypeScript";
  }

  return segment[0].toUpperCase() + segment.slice(1);
}

function getKnownTitle(slug: string) {
  const titles: Record<string, string> = {
    "guardrails-typescript": "Guardrails TypeScript",
    "package-readme-md": "Package README.md",
    "prefer-md-extension": "Prefer .md Extension",
  };

  return titles[slug];
}

function buildRuleDocLiteral(ruleDoc: RuleDoc) {
  return [
    "  {",
    `    slug: ${JSON.stringify(ruleDoc.slug)},`,
    `    title: ${JSON.stringify(ruleDoc.title)},`,
    `    summary: ${JSON.stringify(ruleDoc.summary)},`,
    `    markdown: ${JSON.stringify(ruleDoc.markdown)},`,
    `    ruleSourcePath: ${JSON.stringify(ruleDoc.ruleSourcePath)},`,
    `    docsSourcePath: ${JSON.stringify(ruleDoc.docsSourcePath)},`,
    "  }",
  ].join("\n");
}

function buildGroupDocLiteral(groupDoc: GroupDoc) {
  return [
    "  {",
    `    slug: ${JSON.stringify(groupDoc.slug)},`,
    `    title: ${JSON.stringify(groupDoc.title)},`,
    `    summary: ${JSON.stringify(groupDoc.summary)},`,
    `    markdown: ${JSON.stringify(groupDoc.markdown)},`,
    `    ruleSlugs: ${JSON.stringify(groupDoc.ruleSlugs)},`,
    "  }",
  ].join("\n");
}
